config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :prayers, except: [:edit, :update] do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :prayer
  belongs_to :god
  validates :description, presence: :true, uniqueness: true
  validates :prayer, uniqueness: { scope: :god }
end

app/models/god.rb
class God < ApplicationRecord
  has_many :comments
  has_many :prayers, through: :comments
  validates :name, presence: :true, uniqueness: true
  has_one_attached :photo
end

app/models/prayer.rb
class Prayer < ApplicationRecord
  has_one :comment, dependent: :destroy
  has_one :god, through: :comment
  validates :name, :pray, presence: true
  has_one_attached :photo
  # validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @gods = God.where(name: ["Zeus", "Hera", "Poseidon", "Demeter", "Ares", "Athena", "Apollo", "Artemis", "Hephaestus", "Aphrodite", "Hermes", "Dionysus", "Hades", "Hypnos", "Nike", "Janus", "Nemesis", "Iris", "Hecate", "Tyche" ])
    @prayer = Prayer.find(params[:prayer_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @prayer = Prayer.find(params[:prayer_id])
    @comment.prayer = @prayer
    if @comment.save
      redirect_to prayers_path
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to prayers_path
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :god_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
  before_action :set_prayer, only: [:show, :destroy]

  def index
    @prayers = Prayer.all
  end

  def show
  end

  def new
    @prayer = Prayer.new
  end

  def create
    @prayer = Prayer.new(prayer_params)
    if @prayer.save
      redirect_to prayers_path
    else
      render :new
    end
  end

  def destroy
    @prayer.destroy
    redirect_to prayers_path
  end

  private

  def set_prayer
    @prayer = Prayer.find(params[:id])
  end

  def prayer_params
    params.require(:prayer).permit(:name, :pray, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="from-flex">
  <div class="form">
    <div class="form-div">
      <%= simple_form_for [@prayer, @comment] do |f| %>
        <div class="form-info">
          <%= f.input :description, label: "Add more details to your pray", input_html: { maxlength: 100} %>
        </div>
        <div class="form-info">
          <%= f.association :god, label: "Select a god to help your prayer!", collection: @gods, include_blank: false %>
        </div>
        <div class="form-button">
          <%= f.submit "new god", class: 'button-all' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Greek Gods</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/banner" %>

app/views/prayers/index.html.erb
<div class="container-cards">
  <div class="cards">
    <% @prayers.each do |prayer| %>
      <% if prayer.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path prayer.photo.key, height:400, width: 300 %>')">
          <%= link_to "", prayer_path(prayer), class: "card-link" %>
          <div class="card-god-pic">
            <div class="card-god-pic-photo">
              <% if prayer.god && prayer.god.photo.attached? %>
                <%= cl_image_tag prayer.god.photo.key, class: "god-pic", height: 100, width: 100, crop: :fill %>
              <% else %>
                <%= cl_image_tag("lego_gods", class: "god-pic", height: 100, width: 100, crop: :fill) %>
              <% end %>
            </div>
            <div class="card-god-pic-name">
              <span><%= prayer.name.capitalize %></span>
            </div>
          </div>
        </div>
      <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path("greece", height: 600, width: 400, crop: :fill) %>')">
          <%= link_to "", prayer_path(prayer), class: "card-link" %>
          <div class="card-god-pic">
            <div class="card-god-pic-photo">
              <% if prayer.god && prayer.god.photo.attached? %>
                <%= cl_image_tag prayer.god.photo.key, class: "god-pic", height: 100, width: 100, crop: :fill %>
              <% else %>
                <%= cl_image_tag("lego_gods", class: "god-pic", height: 100, width: 100, crop: :fill) %>
              <% end %>
            </div>
            <div class="card-god-pic-name">
              <%= prayer.name.capitalize %>
            </div>
          </div>
        </div>
      <% end %>
    <%end %>
  </div>
</div>

app/views/prayers/new.html.erb
<div class="from-flex">
  <div class="form">
    <div class="form-div">
      <%= simple_form_for @prayer do |f| %>
        <div class="form-info">
          <%= f.input :name, label: "Your name please"  %>
        </div>
        <div class="form-info">
          <%= f.input :pray, label: "What you want to pray for?", collection: ["Love", "Study", "Health", "Money", "Smite", "Good Luck", "Bad Voodoo", "Bad Luck", "Stomach acke"], include_blank: false %>
        </div>
        <div class="form-info">
          <%= f.input :photo, label: "Add a picture to help your prayer", as: :file %>
        </div>
        <div class="form-button">
          <%= f.submit "New Prayer", class: 'button-all'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/prayers/show.html.erb
<div class="content-card-show">
  <div class="container-button-destroy">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        What you want to do?
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "Add a God!", new_prayer_comment_path(@prayer), class: "button-all dropdown-item"%>
        <%= link_to "Destroy a prayer!", prayer_path, method: :delete, data: { confirm: "Destroy #{@prayer.name} pray?"}, class: "button-all dropdown-item"%>
        <% if @prayer.comment %>
          <%= link_to "Destroy a god!", comment_path(@prayer.comment), method: :delete, data: { confirm: "Do you dare DESTROY ME!, the Greek god #{@prayer.comment.god.name if @prayer.comment}, YOU WILL PAY WITH YOUR LIFE FILTHY HUMAN"}, class: "button-all dropdown-item" %>
          <!-- <i class="fas fa-meteor"></i> -->
        <% else %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-trip">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
    <div class="card-trip-infos">
      <div>
        <h2><%= @prayer.name.capitalize %></h2>
        <p><%= @prayer.pray.capitalize %></p>
      </div>
      <h2 class="card-trip-pricing"><%= @prayer.comment.description.capitalize if @prayer.comment %></h2>
      <h2 class="card-trip-pricing"><%= @prayer.god.name.capitalize if @prayer.god %></h2>
      <%#= cl_image_tag @prayer.god.photo.key, height: 50, width: 50, crop: :fill, class: "card-trip-user avatar-bordered" %>
      <% if @prayer.god && @prayer.god.photo.attached?%>
        <%= cl_image_tag @prayer.god.photo.key, height: 50, width: 50, crop: :fill, class: "card-trip-user avatar-bordered" %>
      <% else %>
        <%#= cl_image_tag("lego_gods", width: 400, height: 300, crop: :fill) %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.shopify.com/s/files/1/0245/3264/8041/articles/SHOP_HISTORY_GREEKGODS_2019_3X2_8c3fc105-d657-4d58-8e6b-b1e91d29acf1_1200x1200.jpg?v=1558683543);">
  <div class="container">
    <h1>Pray to your favorite <strong> Greek God</strong></h1>
    <span id="banner-typed-text", style="color: white">Change your life Pray for love, luck or even smite your enemies!</span>
    <div class="btn-group">
      <%= link_to "Pray now!", new_prayer_path, class: "button-all", id: "button" %>
      <button type="button" class="dropdown-toggle dropdown-toggle-split button-all" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <div class="dropdown-menu">
        <%= link_to "prayers!", prayers_path, class: "dropdown-item button-all" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/antonioist" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/antoniosancheztrespalacios/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/aitrespalacios" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/antonio04398356" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/in/antonio-isidoro-s%C3%A1nchez-trespalacios-/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Made by Antonio
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "button-all" do %>
    <i class="fas fa-home"></i>
  <% end %>
  <%= cl_image_tag "antonio", class: "avatar"%>
</div>